<?php

namespace App\Http\Controllers\Marketing;

use App\Http\Controllers\Controller;
use App\Models\Proyek;
use App\Models\Penawaran;
use App\Models\PenawaranDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class PenawaranController extends Controller
{
    public function index()
    {
        $penawaranData = Penawaran::with(['proyek', 'details'])->get();
        return view('pages.marketing.penawaran.index', compact('penawaranData'));
    }

    public function show($proyekId)
    {
        // Get project data with project barang
        $proyek = Proyek::with('proyekBarang')->findOrFail($proyekId);

        // Get or create penawaran for this project (ambil yang terakhir)
        $penawaran = Penawaran::where('id_proyek', $proyek->id_proyek)
                             ->orderBy('id_penawaran', 'desc')
                             ->first();

        if (!$penawaran) {
            // Create new penawaran (all default values will be auto-generated by model event)
            $penawaran = Penawaran::create([
                'id_proyek' => $proyek->id_proyek,
                'tanggal_penawaran' => now(),
                'status' => 'Menunggu'
            ]);
        }

        // Get penawaran details
        $penawaranDetails = PenawaranDetail::where('id_penawaran', $penawaran->id_penawaran)->get();

        // Jika belum ada detail penawaran, buat dari data proyek_barang
        if ($penawaranDetails->count() == 0 && $proyek->proyekBarang && $proyek->proyekBarang->count() > 0) {
            foreach ($proyek->proyekBarang as $barang) {
                $subtotal = $barang->harga_satuan ? $barang->harga_satuan * $barang->jumlah : 0;

                PenawaranDetail::create([
                    'id_penawaran' => $penawaran->id_penawaran,
                    'nama_barang' => $barang->nama_barang,
                    'qty' => $barang->jumlah,
                    'satuan' => $barang->satuan ?? 'Unit', // Tambahkan field satuan
                    'harga_satuan' => $barang->harga_satuan ?? 0,
                    'subtotal' => $subtotal,
                    'spesifikasi' => $barang->spesifikasi ?? ''
                ]);
            }

            // Reload penawaran details after creation
            $penawaranDetails = PenawaranDetail::where('id_penawaran', $penawaran->id_penawaran)->get();
        }        // Auto-update total nilai berdasarkan detail yang ada
        if ($penawaranDetails->count() > 0) {
            $calculatedTotal = $penawaranDetails->sum('subtotal');
            if ($penawaran->total_nilai != $calculatedTotal) {
                $penawaran->total_nilai = $calculatedTotal;
                $penawaran->save();
            }
        }

        return view('pages.marketing.penawaran.detail', compact('proyek', 'penawaran', 'penawaranDetails'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'id_proyek' => 'required|exists:proyek,id_proyek',
            'tanggal_penawaran' => 'required|date',
            'catatan' => 'nullable|string',
            'surat_penawaran' => 'nullable|file|mimes:pdf,doc,docx|max:5120',
            'surat_pesanan' => 'nullable|file|mimes:pdf,doc,docx|max:5120',
        ]);

        try {
            DB::beginTransaction();

            // Flag untuk tracking upload surat penawaran
            $suratPenawaranUploaded = false;

            // Create or update penawaran
            $penawaran = Penawaran::updateOrCreate(
                ['id_proyek' => $request->id_proyek],
                [
                    'tanggal_penawaran' => $request->tanggal_penawaran,
                    'catatan' => $request->catatan,
                    'status' => 'Menunggu'
                ]
            );

            // Auto-calculate total_nilai dari detail penawaran
            $penawaranDetails = PenawaranDetail::where('id_penawaran', $penawaran->id_penawaran)->get();
            if ($penawaranDetails->count() > 0) {
                $penawaran->total_nilai = $penawaranDetails->sum('subtotal');
            }

            // Handle file uploads
            if ($request->hasFile('surat_penawaran')) {
                // Delete old file if exists
                if ($penawaran->surat_penawaran && Storage::exists('public/penawaran/' . $penawaran->surat_penawaran)) {
                    Storage::delete('public/penawaran/' . $penawaran->surat_penawaran);
                }

                $file = $request->file('surat_penawaran');
                $filename = time() . '_penawaran_' . $file->getClientOriginalName();
                $file->storeAs('public/penawaran', $filename);
                $penawaran->surat_penawaran = $filename;
                $suratPenawaranUploaded = true;
            }

            if ($request->hasFile('surat_pesanan')) {
                // Delete old file if exists
                if ($penawaran->surat_pesanan && Storage::exists('public/penawaran/' . $penawaran->surat_pesanan)) {
                    Storage::delete('public/penawaran/' . $penawaran->surat_pesanan);
                }

                $file = $request->file('surat_pesanan');
                $filename = time() . '_pesanan_' . $file->getClientOriginalName();
                $file->storeAs('public/penawaran', $filename);
                $penawaran->surat_pesanan = $filename;
            }

            $penawaran->save();

            // Update status proyek menjadi 'pembayaran' jika surat penawaran di-upload
            if ($suratPenawaranUploaded) {
                $proyek = Proyek::find($request->id_proyek);
                if ($proyek) {
                    $proyek->status = 'pembayaran';
                    $proyek->save();
                }

                // Update status penawaran menjadi 'ACC' (approved)
                $penawaran->status = 'ACC';
                $penawaran->save();
            }

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => $suratPenawaranUploaded ?
                    'Penawaran berhasil disimpan dan status proyek diubah ke pembayaran!' :
                    'Penawaran berhasil disimpan!',
                'data' => $penawaran,
                'status_changed' => $suratPenawaranUploaded
            ]);

        } catch (\Exception $e) {
            DB::rollback();

            // Log error untuk debugging
            Log::error('Penawaran store error: ' . $e->getMessage());
            Log::error('Stack trace: ' . $e->getTraceAsString());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan: ' . $e->getMessage(),
                'debug' => config('app.debug') ? $e->getTraceAsString() : null
            ], 500);
        }
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'tanggal_penawaran' => 'required|date',
            'catatan' => 'nullable|string',
            'surat_penawaran' => 'nullable|file|mimes:pdf,doc,docx|max:5120',
            'surat_pesanan' => 'nullable|file|mimes:pdf,doc,docx|max:5120',
        ]);

        try {
            DB::beginTransaction();

            $penawaran = Penawaran::findOrFail($id);

            $penawaran->tanggal_penawaran = $request->tanggal_penawaran;
            $penawaran->catatan = $request->catatan;

            // Auto-calculate total_nilai dari detail penawaran
            $penawaranDetails = PenawaranDetail::where('id_penawaran', $penawaran->id_penawaran)->get();
            if ($penawaranDetails->count() > 0) {
                $penawaran->total_nilai = $penawaranDetails->sum('subtotal');
            }

            // Flag untuk tracking upload surat penawaran
            $suratPenawaranUploaded = false;

            // Handle file uploads
            if ($request->hasFile('surat_penawaran')) {
                // Delete old file if exists
                if ($penawaran->surat_penawaran && Storage::exists('public/penawaran/' . $penawaran->surat_penawaran)) {
                    Storage::delete('public/penawaran/' . $penawaran->surat_penawaran);
                }

                $file = $request->file('surat_penawaran');
                $filename = time() . '_penawaran_' . $file->getClientOriginalName();
                $file->storeAs('public/penawaran', $filename);
                $penawaran->surat_penawaran = $filename;
                $suratPenawaranUploaded = true;
            }

            if ($request->hasFile('surat_pesanan')) {
                // Delete old file if exists
                if ($penawaran->surat_pesanan && Storage::exists('public/penawaran/' . $penawaran->surat_pesanan)) {
                    Storage::delete('public/penawaran/' . $penawaran->surat_pesanan);
                }

                $file = $request->file('surat_pesanan');
                $filename = time() . '_pesanan_' . $file->getClientOriginalName();
                $file->storeAs('public/penawaran', $filename);
                $penawaran->surat_pesanan = $filename;
            }

            $penawaran->save();

            // Update status proyek menjadi 'pembayaran' jika surat penawaran di-upload
            if ($suratPenawaranUploaded) {
                $proyek = Proyek::find($penawaran->id_proyek);
                if ($proyek) {
                    $proyek->status = 'pembayaran';
                    $proyek->save();
                }

                // Update status penawaran menjadi 'ACC' (approved)
                $penawaran->status = 'ACC';
                $penawaran->save();
            }

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => $suratPenawaranUploaded ?
                    'Penawaran berhasil diupdate dan status proyek diubah ke pembayaran!' :
                    'Penawaran berhasil diupdate!',
                'data' => $penawaran,
                'status_changed' => $suratPenawaranUploaded
            ]);

        } catch (\Exception $e) {
            DB::rollback();

            // Log error untuk debugging
            Log::error('Penawaran update error: ' . $e->getMessage());
            Log::error('Stack trace: ' . $e->getTraceAsString());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan: ' . $e->getMessage(),
                'debug' => config('app.debug') ? $e->getTraceAsString() : null
            ], 500);
        }
    }

    public function downloadFile($type, $filename)
    {
        $path = 'public/penawaran/' . $filename;

        if (!Storage::exists($path)) {
            abort(404, 'File tidak ditemukan');
        }

        return Storage::download($path);
    }
}
